# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
#用QT DESIGNER設計框架再用CMD指令:python -m PyQt5.uic.pyuic -x main.ui -o pyqt5.py
#https://www.youtube.com/watch?v=_3zLU47lEM0 連MYSQL
#https://www.youtube.com/watch?v=xL2NdSubiNY 抓CSV並塞進tabwidget 框架
#https://www.youtube.com/watch?v=DQkDWsHYxq8 計時抓圖片與CSV

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QPixmap
from PyQt5.QtCore import QTimer
from PyQt5.QtWidgets import QAbstractItemView, QHeaderView
import pymysql
import pandas as pd
import configparser

config = configparser.ConfigParser()
config.read('config.ini')


db = config.get('mysql', 'db')
user = config.get('mysql', 'user')
password = config.get('mysql',"password")
host = config.get('mysql',"host")
port = int(config.get('mysql', "port"))

class Ui_Form(object):
    def koneksi(self):
        con = pymysql.connect(db=db,user=user,password=password,host=host,port=port,autocommit=True)
        cur = con.cursor()
        if(cur):
            self.messagebox("提醒","準備開啟物流視窗")
        else:
            self.messagebox("提醒","準備開啟物流視窗")
    def messagebox(self, title,message):
        mess = QtWidgets.QMessageBox()
        mess.setWindowTitle(title)
        mess.setText(message)
        mess.setStandardButtons(QtWidgets.QMessageBox.Ok)
        mess.exec_()
    def tampil(self):
        sku = self.plainTextEdit.toPlainText()
        db_1 = pymysql.connect(db=db,user=user,password=password,host=host,port=port,autocommit=True)
        cursor = db_1.cursor()
        cursor.execute("SELECT * FROM AioT.product where sku = '" + str(sku) + "'")
        data = cursor.fetchall()
        if(data):
            for tp in data:
                self.plainTextEdit.setPlainText(""+tp[9])
                self.plainTextEdit_2.setPlainText(""+tp[1])
        else:
            self.messagebox("錯誤","沒有這項商品紀錄")
    def clear(self):
        self.plainTextEdit.setPlainText("")
        self.plainTextEdit_2.setPlainText("")
    def PIC(self):
        self.label.setPixmap(QPixmap("./img/1.jpg"))
        self.label.setScaledContents(True)

    def CSV(self):
        df = pd.read_csv(r"csv/2.csv")
        d_records = df.to_dict('records')
        print(d_records)
        row = 0
        self.tableWidget.setRowCount(len(d_records))
        for i in d_records:
            self.tableWidget.setItem(row, 0, QtWidgets.QTableWidgetItem(i["number"]))
            self.tableWidget.setItem(row, 1, QtWidgets.QTableWidgetItem(i["class"]))
            sku = i["number"]
            db_1 = pymysql.connect(db=db,user=user,password=password,host=host,port=port,autocommit=True)
            cursor = db_1.cursor()
            cursor.execute("SELECT * FROM AioT.product where sku = '" + str(sku) + "'")
            data = cursor.fetchall()
            if (data):
                for tp in data:
                    self.tableWidget.setItem(row, 2, QtWidgets.QTableWidgetItem("" + tp[1]))
            else:
                self.tableWidget.setItem(row, 2, QtWidgets.QTableWidgetItem("沒有這項商品"))
            row += 1

    def start(self):
        self.timer.start()
    def stop(self):
        self.timer.stop()

    def setupUi(self, Form):
        self.koneksi()
        Form.setObjectName("Form")
        Form.resize(1126, 817)
        Form.setAutoFillBackground(False)
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.resize(1126, 817)
        self.label_7.setStyleSheet("background-color: #323232")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(20, 70, 511, 451))
        self.label.setStyleSheet("background-color: black")
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(20, 20, 161, 31))
        self.label_2.setStyleSheet("color:cyan")
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(70, 560, 93, 31))
        self.pushButton.setStyleSheet("color:red;background-color: beige")
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.start)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(600, 20, 121, 31))
        self.label_3.setStyleSheet("color:cyan")
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.tableWidget = QtWidgets.QTableWidget(Form)
        self.tableWidget.setGeometry(QtCore.QRect(600, 70, 441, 331))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.tableWidget.setFont(font)
        self.tableWidget.setMouseTracking(False)
        self.tableWidget.setTextElideMode(QtCore.Qt.ElideLeft)
        self.tableWidget.setRowCount(10)
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.tableWidget.horizontalHeader().setStyleSheet("QHeaderView::section{color:red;background:yellow;}");
        self.tableWidget.horizontalHeader().setStretchLastSection(True)#//設置充滿表寬度
        self.tableWidget.setEditTriggers(QAbstractItemView.NoEditTriggers) # 設定表格不可編輯
        self.tableWidget.horizontalHeader().resizeSection(2, 520) # //設置第三列默認列寬
        self.tableWidget.horizontalHeader().setDefaultSectionSize(150) # //設置默認列寬
        self.tableWidget.horizontalHeader().setMinimumSectionSize(47) #設置列寬最小值
        self.tableWidget.verticalHeader().setDefaultSectionSize(40) # //設置默認行高
        self.tableWidget.verticalHeader().setMinimumSectionSize(45) #設置列寬最小值
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(370, 560, 93, 31))
        self.pushButton_2.setStyleSheet("color:blue;background-color: beige")
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.stop)
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(600, 420, 121, 31))
        self.label_4.setStyleSheet("color:cyan")
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(Form)
        self.plainTextEdit.setGeometry(QtCore.QRect(710, 460, 331, 31))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.plainTextEdit.setFont(font)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(600, 460, 111, 31))
        self.label_5.setStyleSheet("color:white")
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(600, 500, 111, 31))
        self.label_6.setStyleSheet("color:white")
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(Form)
        self.plainTextEdit_2.setGeometry(QtCore.QRect(710, 500, 331, 31))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.plainTextEdit_2.setFont(font)
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(600, 560, 93, 31))
        self.pushButton_3.setStyleSheet("color:red;background-color: beige")
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_3.clicked.connect(self.tampil)
        self.pushButton_4 = QtWidgets.QPushButton(Form)
        self.pushButton_4.setGeometry(QtCore.QRect(950, 560, 93, 31))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_4.setStyleSheet("color:blue;background-color: beige")
        self.pushButton_4.clicked.connect(self.clear)
        self.timer = QTimer()
        self.timer.timeout.connect(self.PIC)
        self.timer.timeout.connect(self.CSV)
        self.timer.setInterval(1000)
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "物流"))
        self.label.setText(_translate("Form", "圖片"))
        self.label_2.setText(_translate("Form", "辨識圖片:"))
        self.pushButton.setText(_translate("Form", "開始"))
        self.label_3.setText(_translate("Form", "商品類別:"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "商品編號:"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "商品類別:"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "商品名稱:"))
        self.pushButton_2.setText(_translate("Form", "停止"))
        self.label_4.setText(_translate("Form", "商品查詢:"))
        self.label_5.setText(_translate("Form", "商品編號:"))
        self.label_6.setText(_translate("Form", "商品名稱:"))
        self.pushButton_3.setText(_translate("Form", "查詢"))
        self.pushButton_4.setText(_translate("Form", "清除"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
